config/routes.rb
Rails.application.routes.draw do
  get "top/index", to: "top#index"
  get "top/new", to: "top#new"
  get "top/show/:id", to: "top#show", as: :top_show
  get "top/edit/:id", to: "top#edit", as: :top_edit
  post "newdates", to: "top#create"
  patch "top/:id", to: "top#update", as: :newdate
  delete "top/:id", to: "top#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  resources :newdates
  resources :top
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/newdate.rb
class Newdate < ApplicationRecord
    validates :title, presence: true, length: { maximum: 20 }
    validates :startday, presence: true
    validates :endday, presence: true

    validate :expiration_date_cannot_be_in_the_past
    def expiration_date_cannot_be_in_the_past
        return if startday.blank? || endday.blank?
        if endday < startday
        errors.add(:endday, "は開始日より前の日付は使えません")
        end
    end

    validates :memo, length: { maximum: 500 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @newdate = Newdate.all
  end

  def new
    @newdate = Newdate.new
  end

  def create
    @newdate = Newdate.new(params.require(:newdate).permit(:title, :startday, :endday, :allday, :memo))
    if @newdate.save
      flash[:notice] = "スケジュールを新規登録しました"
      redirect_to top_index_path
    else
      render "new", status: :unprocessable_entity
    end
  end

  def show
    @newdate = Newdate.find_by(id: params[:id])
  end

  def edit
    @newdate = Newdate.find_by(id: params[:id])
  end

  def update
    @newdate = Newdate.find_by(id: params[:id])
    if @newdate.update(params.require(:newdate).permit(:title, :startday, :allday, :endday, :memo))
      flash[:notice] = "「#{@newdate.id}」の情報を更新しました"
      redirect_to top_index_path
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @newdate = Newdate.find_by(id: params[:id])
    @newdate.destroy
    flash[:notice] = "スケジュールを削除しました"
    redirect_to top_index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= javascript_importmap_tags %>
    <title><%= content_for(:title) || "Schedule" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="turbolinks-visit-control" content="reload">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.10.0/js/bootstrap-datepicker.min.js" integrity="sha512-LsnSViqQyaXpD4mBBdRYeP6sRwJiJveh2ZIbW41EBrNmKxgr/LFZIiWT6yr+nycvhvauz8c2nYMhrP80YhG7Cw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.10.0/css/bootstrap-datepicker3.min.css" integrity="sha512-aQb0/doxDGrw/OC7drNaJQkIKFu6eSWnVMAwPN64p6sZKeJ4QCDYL42Rumw2ZtL8DB9f66q4CnLIUnAw28dEbg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= yield :css %>
  </head>

  <body>
    <header class="header">
      <div class="top">
        <span class="top-title">
          スケジュール管理アプリ
        </span>
      </div>
    </header>
    <%= yield %>


  </body>
</html>

app/views/top/edit.html.erb
<%= stylesheet_link_tag "edit", "data-turbo-track": "reload" %>

<div class="all-edit">

<h2 class="title">
    予定を編集してください
</h2>

<% if @newdate.errors.any? %>
    <div id="error_explanation">
        <h2><%= @newdate.errors.count %>件のエラーが発生しました:</h2>
        <ul>
            <% @newdate.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
    <% end %>


<div class="edit-form">
<%= form_with model: @newdate, local: true do |f| %>

    <div class="table">
        <div class="edit-tr">
            <ul class="must">
                <li class="kome"><label><%= f.label :title ,"タイトル", :class =>"form-title" %></label></li>
                <li class="kome">*</li>
            </ul>
            <%= f.text_field :title, :class =>"form-text" %>
        </div>

        <ul class="ul-day">
            <li class="li-day">
                <div class="edit-tr">
                    <ul class="must">
                        <li class="kome"><label><%= f.label :startday ,"開始日", :class =>"form-title" %></label></li>
                        <li class="kome">*</li>
                    </ul>
                    <%= f.date_field :startday, :class =>"form-text" %>
                </div>
            </li>

            <li class="li-day">
                <div class="edit-tr">
                    <ul class="must">
                        <li class="kome"><label><%= f.label :endday ,"終了日", :class =>"form-title" %></label></li>
                        <li class="kome">*</li>
                    </ul>
                    <%= f.date_field :endday, :class =>"form-text" %>
                </div>
            </li>
        </ul>

        <div class="edit-check">
            <%=f.check_box :allday, {}, "〇", "" %>
            <span>終日の場合はチェックを入れます</span>
        </div>

        <div class="edit-tr">
            <label><%= f.label :memo ,"スケジュールメモ", :class =>"form-title" %></label>
            <%= f.text_area :memo, :class =>"form-text" %>
        </div>
    </div>


    <div class="hozon">
        <ul class="ul">
            <li><%= link_to "キャンセル",  top_index_path, :class =>"cansel" %></li>
            <li><%= f.submit "保存",  :class => "submit" %></li>
        </ul>
    </div>
    <% end %>
    </div>

    </div>

<script>$('.datepicker').datepicker();</script>


app/views/top/index.html.erb
<%= stylesheet_link_tag "index", "data-turbo-track": "reload" %>

<div class="all-index">
<div class="index-top">
    <span class="title">
        予定一覧
    </span>
    <a href="/top/new">
        <button class="new-cre">
            <img class="plus" src="https://sato-icons.com/wp/wp-content/uploads/2021/05/%E3%83%97%E3%83%A9%E3%82%B9%E3%81%AE%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B32.svg" width="35" height="35">
            新規作成
        </button>
    </a>
</div>

<% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
<% end %>

<table class="index-list">
    <thead>
        <tr>
            <th>ID</th>
            <th>タイトル</th>
            <th>開始日</th>
            <th>終了日</th>
            <th>終日</th>
            <th>更新日時</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        <% @newdate.each do |newdate| %>
        <tr>
            <td><%= newdate.id %></td>
            <td><%= newdate.title %></td>
            <td><%= newdate.startday.strftime('%Y-%m-%d') %></td>
            <td><%= newdate.endday.strftime('%Y-%m-%d') %></td>
            <td><% if newdate.allday == true %>〇<% end %></td>
            <td><%= newdate.updated_at.to_fs(:datetime_jp) %></td>
            <td><%= link_to "詳細", top_show_path(newdate.id) %></td>
            <td><%= link_to "編集", top_edit_path(newdate.id) %></td>
            <td><%= link_to "削除", top_path(newdate.id), data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？",} %></td>
        </tr>
    <% end %>
    </tbody>
</table>

<div class="sum">
    <div class="sum-title">
        <span class="sum-text">
            予定合計
        </span>
        <span class="sum-num">
            <%= @newdate.count %>
        </span>
        <span class="sum-text">
            件
        </span>
    </div>
    <span class="today"><%= Time.zone.today.strftime('本日の日付 %Y/%m/%d') %></span>
</div>
</div>

app/views/top/new.html.erb
<%= stylesheet_link_tag "new", "data-turbo-divack": "reload" %>

<div class="all-new">
<h2 class="title">
    予定の新規追加
</h2>

<div class="new-form">
<%= form_with model: @newdate do |f| %>

    <% if @newdate.errors.any? %>
    <div id="error_explanation">
        <h2><%= @newdate.errors.count %>件のエラーが発生しました:</h2>
        <ul>
            <% @newdate.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
    <% end %>

    <div class="table">
        <div class="new-tr">
            <ul class="must">
                <li class="kome"><label><%= f.label :title ,"タイトル", :class =>"form-title" %></label></li>
                <li class="kome">*</li>
            </ul>
            <%= f.text_field :title, :class =>"form-text" %>
        </div>

        <ul class="ul-day">
            <li class="li-day">
                <div class="new-tr">
                    <ul class="must">
                        <li class="kome"><label><%= f.label :startday ,"開始日", :class =>"form-title" %></label></li>
                        <li class="kome">*</li>
                    </ul>
                    <%= f.date_field :startday, :class =>"form-text" %>
                </div>
            </li>

            <li class="li-day">
                <div class="new-tr">
                    <ul class="must">
                        <li class="kome"><label><%= f.label :endday ,"終了日", :class =>"form-title" %></label></li>
                        <li class="kome">*</li>
                    </ul>
                    <%= f.date_field :endday, :class =>"form-text" %>
                </div>
            </li>
        </ul>

        <div class="new-check">
            <%=f.check_box :allday, {}, "〇", "" %>
            <span>終日の場合はチェックを入れます</span>
        </div>

        <div class="new-tr">
            <label><%= f.label :memo ,"スケジュールメモ", :class =>"form-title" %></label>
            <%= f.text_area :memo, :class =>"form-text" %>
        </div>
    </div>

    <div class="hozon">
        <ul class="ul">
            <li><%= link_to "キャンセル",  top_index_path, :class =>"cansel" %></li>
            <li><%= f.submit "保存",  :class => "submit" %></li>
        </ul>
    </div>
<% end %>
</div>

<script>$('.datepicker').datepicker();</script>

app/views/top/show.html.erb
<%= stylesheet_link_tag "show", "data-turbo-track": "reload" %>

<div class="show">
<section class="section">

<a class="back-index" href="/top/index">
    <div class="index">
        <img class="svg" src="https://sato-icons.com/wp/wp-content/uploads/2020/10/%E5%89%8D%E3%81%AB%E6%88%BB%E3%82%8B%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B33.svg" width="30" height="30">
        <%= link_to "一覧に戻る", top_index_path, :class =>"index-title" %>
    </div>
</a>

<div class="title">
    <p class="schedule"><%= @newdate.title%></p>
    <a class="to-edit">
        <button class="btn">
            <img class="svg" src ="https://sato-icons.com/wp/wp-content/uploads/2021/08/%E9%89%9B%E7%AD%86%E3%81%AE%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B3.svg" width="30" height="30">
            <%= link_to "編集", top_edit_path, :class =>"btn-title" %>
        </button>
    </a>
</div>

<div class="show-data">
    <table class="show-table">
        <tr>
            <th>開始日</th>
            <td><%= @newdate.startday %></td>
        </tr>
        <tr>
            <th>終了日</th>
            <td><%= @newdate.endday %></td>
        </tr>
        <tr>
            <th>終日</th>
            <td><% if @newdate.allday == true %>〇<% end %></td>
        </tr>
        <tr>
            <th>スケジュールメモ</th>
            <td><%= @newdate.memo %></td>
        </tr>
    </table>
</div>


</section>
</div>
